### ISSUE TITLE
IP is not logged correctly into the activity logs

### ISSUE THREAD

**Issue by migue802** [hudikhq/hoodik#85] opened 2024-03-11 19:50 UTC
Hoodik doesn't properly log the IPs of the users on the User Sessions

Logs when Docker Container isn't deattatched:
![image](https://github.com/hudikhq/hoodik/assets/54627022/45c61049-9089-4e1b-9f2d-bec6a224a6a1)

Web app:
![image](https://github.com/hudikhq/hoodik/assets/54627022/4a547498-9150-43d1-884b-403ca6ddff24)

Some details to note:
I've installed Hoodik via Docker, and used Nginx Proxy Manager to proxy everything.

Also, one question, is it possible to disable HTTPS on Hoodik, so connections can be accepted by Nginx Proxy manager and therefore use a Lets Encrypt cert issued by Nginx proxy manager to encrypt outside connections?

**Comment by migue802** [comment] 2024-03-15 13:42
After restarting the whole server (for other reasons) the issue dissapeared, can't repro again

**Comment by htunlogic** [comment] 2024-03-18 07:13
@migue802, thanks for the update. I couldn't reproduce the issue myself, so I will close it. If you manage to reproduce it, please reopen it.

**Closed by htunlogic** 2024-03-18 07:13 UTC
Labels: bug
